{{- if .Values.extraWebhookTemplates }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tracker-templates
  labels:
    {{- include "tracker.labels" . | nindent 4 }}
data:
  {{- range .Values.extraWebhookTemplates }}
  {{ .name }}: | {{ .goTemplate | nindent 4 }}
  {{- end }}
{{- end }}
